/*
 * File: app/view/ContactUsForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.ContactUsForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.contactusform',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.HtmlEditor'
    ],

    height: 400,
    width: 600,
    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'closeBtn',
                            iconCls: 'delete',
                            text: 'Close'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            itemId: 'sendBtn',
                            iconCls: 'add',
                            text: 'Send'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Request for Information',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: 'anchor',
                            items: [
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Which of these types do you represent',
                                    labelWidth: 300,
                                    name: 'requester_type',
                                    allowBlank: false,
                                    editable: false,
                                    displayField: 'info',
                                    store: 'RequesterType',
                                    valueField: 'type'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Name',
                                    labelWidth: 300,
                                    name: 'requester_name',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    hidden: true,
                                    fieldLabel: 'What company/institution do you represent',
                                    labelWidth: 300,
                                    name: 'requester_institution'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Email',
                                    labelWidth: 300,
                                    name: 'requester_email',
                                    inputType: 'email',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    hidden: true,
                                    fieldLabel: 'LandLine',
                                    labelWidth: 300,
                                    name: 'requester_landline'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    hidden: true,
                                    fieldLabel: 'Mobile Number',
                                    labelWidth: 300,
                                    name: 'requester_mobile_number'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    hidden: true,
                                    fieldLabel: 'How best can we contact you',
                                    labelWidth: 300,
                                    name: 'how_to_contact_requester',
                                    editable: false,
                                    displayField: 'contact_mode',
                                    store: 'ContactMethod',
                                    valueField: 'contact_mode'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    hidden: true,
                                    fieldLabel: 'What time is best to contact you',
                                    labelWidth: 300,
                                    name: 'best_time_to_contact_requester',
                                    editable: false,
                                    displayField: 'contact_time',
                                    store: 'TimeOfContact',
                                    valueField: 'contact_time'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    hidden: true,
                                    fieldLabel: 'What day is the best to contact you',
                                    labelWidth: 300,
                                    name: 'best_day_to_contact_requester',
                                    editable: false,
                                    displayField: 'contact_day',
                                    store: 'DayOfContact',
                                    valueField: 'contact_day'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Subject',
                                    labelWidth: 300,
                                    name: 'subject',
                                    allowBlank: false
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 3,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'htmleditor',
                                    height: 200,
                                    fieldLabel: 'Request',
                                    labelWidth: 300,
                                    name: 'request'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});