/*
 * File: app/view/DeliveryAddressForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.DeliveryAddressForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.deliveryaddressform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Radio',
        'Ext.form.field.ComboBox',
        'Ext.form.Label',
        'Ext.form.field.Hidden'
    ],

    height: 585,
    id: 'card-1',
    width: 1000,
    bodyPadding: 10,
    title: '',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    flex: 10,
                    margin: 5,
                    title: 'Address Delivery Information',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 10,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: 5,
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Delivery Address',
                                            items: [
                                                {
                                                    xtype: 'radiofield',
                                                    itemId: 'primaryAddressRadio',
                                                    name: 'address',
                                                    boxLabel: 'Deliver to this address',
                                                    inputValue: 'primary'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 8,
                                    margin: '20 3 0 0',
                                    title: 'Primary Address',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Address1',
                                            name: 'address1',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Address 2',
                                            name: 'address2',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Country',
                                            name: 'country',
                                            readOnly: true,
                                            displayField: 'name',
                                            minChars: 1000,
                                            store: 'Countries',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'State',
                                            name: 'state',
                                            readOnly: true,
                                            displayField: 'name',
                                            minChars: 1000,
                                            store: 'States',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            itemId: 'primaryCityId',
                                            fieldLabel: 'City',
                                            name: 'city',
                                            readOnly: true,
                                            displayField: 'name',
                                            minChars: 1000,
                                            store: 'Cities',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Landmark',
                                            name: 'primary_address_landmark'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Nearest B/Stop',
                                            name: 'primary_address_nearest_bus_stop'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 3,
                                    margin: 5,
                                    title: 'This person can take delivery in my absence',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Reciever Name',
                                            name: 'primary_reciever_name'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Mobile Number',
                                            name: 'primary_reciever_mobile_number'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 10,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: 5,
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Delivery Address',
                                            items: [
                                                {
                                                    xtype: 'radiofield',
                                                    itemId: 'permanentAddressRadio',
                                                    name: 'address',
                                                    boxLabel: 'Deliver to this address',
                                                    inputValue: 'permanent'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 8,
                                    margin: '20 3 0 0',
                                    title: 'Permanent Delivery Address',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Address1',
                                            name: 'delivery_address1',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Address2',
                                            name: 'delivery_address2',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Country',
                                            name: 'delivery_country',
                                            readOnly: true,
                                            displayField: 'name',
                                            minChars: 1000,
                                            store: 'Countries',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'State',
                                            name: 'delivery_state',
                                            readOnly: true,
                                            displayField: 'name',
                                            minChars: 1000,
                                            queryMode: 'local',
                                            store: 'States',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            itemId: 'permanentCityId',
                                            fieldLabel: 'City',
                                            name: 'delivery_city',
                                            readOnly: true,
                                            displayField: 'name',
                                            minChars: 1000,
                                            queryMode: 'local',
                                            store: 'Cities',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Landmark',
                                            name: 'permanent_address_landmark'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Nearest B/Stop',
                                            name: 'permanent_address_nearest_bus_stop'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 3,
                                    margin: 5,
                                    title: 'This person can take delivery in my absence',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Reciever Name',
                                            name: 'permanent_reciever_name'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Mobile Number',
                                            name: 'permanent_reciever_mobile_number'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 10,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: 5,
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Delivery Address',
                                            items: [
                                                {
                                                    xtype: 'radiofield',
                                                    itemId: 'corporateAddressRadio',
                                                    name: 'address',
                                                    boxLabel: 'Deliver to this address',
                                                    inputValue: 'corporate'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 8,
                                    margin: '20 3 0 0',
                                    title: 'Corporate Address (Corporate Members only)',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Address1',
                                            name: 'corporate_address1',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Address2',
                                            name: 'corporate_address2',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Country',
                                            name: 'corporate_country',
                                            readOnly: true,
                                            displayField: 'name',
                                            minChars: 1000,
                                            store: 'Countries',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'State',
                                            name: 'corporate_state',
                                            readOnly: true,
                                            displayField: 'name',
                                            minChars: 1000,
                                            store: 'States',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            itemId: 'corporateCityId',
                                            fieldLabel: 'City',
                                            name: 'corporate_city',
                                            readOnly: true,
                                            displayField: 'name',
                                            minChars: 1000,
                                            store: 'Cities',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Landmark',
                                            name: 'corporate_address_landmark'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Nearest B/Stop',
                                            name: 'corporate_address_nearest_bus_stop'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 3,
                                    margin: 5,
                                    title: 'This person can take delivery in my absence',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Reciever Name',
                                            name: 'corporate_reciever_name'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Mobile Number',
                                            name: 'corporate_reciever_mobile_number'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 10,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: 5,
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Delivery Address',
                                            items: [
                                                {
                                                    xtype: 'radiofield',
                                                    itemId: 'preferredAddressRadio',
                                                    name: 'address',
                                                    boxLabel: 'Deliver to this address',
                                                    inputValue: 'special'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 8,
                                    margin: '20 3 0 0',
                                    title: 'A New Address for this Order',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Address1',
                                            name: 'order_address1'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Address2',
                                            name: 'order_address2'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            itemId: 'specialCountryCombo',
                                            fieldLabel: 'Country',
                                            name: 'order_country',
                                            editable: false,
                                            displayField: 'name',
                                            store: 'Countries',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            itemId: 'specialStateCombo',
                                            fieldLabel: 'State',
                                            name: 'order_state',
                                            editable: false,
                                            displayField: 'name',
                                            queryMode: 'local',
                                            store: 'StatesInACountry',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            itemId: 'givenCityId',
                                            fieldLabel: 'City',
                                            name: 'order_city',
                                            editable: false,
                                            displayField: 'name',
                                            queryMode: 'local',
                                            store: 'CitiesInAState',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Landmark',
                                            name: 'order_address_landmark'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Nearest B/stop',
                                            name: 'order_address_nearest_bus_stop'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 3,
                                    margin: 5,
                                    title: 'This person can take delivery in my absence',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Reciever Name',
                                            name: 'special_reciever_name'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Mobile Number',
                                            name: 'special_reciever_mobile_number'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    margin: 10,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'fieldset',
                            title: 'Important hamper & gift delivery Information',
                            items: [
                                {
                                    xtype: 'label',
                                    html: '<center><em><strong>For Hamper & Gift Products, the selected delivery address will only serve as the Return address whenever we could not deliver the item to the beneficiary</strong></em></center>'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'country_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'state_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'city_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'delivery_country_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'delivery_state_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'delivery_city_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'corporate_city_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'corporate_state_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'corporate_country_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'order_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'is_delivery_selected'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'selected_delivery_city_id'
                }
            ]
        });

        me.callParent(arguments);
    }

});