/*
 * File: app/view/FundingAnotherMemberWalletForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.FundingAnotherMemberWalletForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.fundinganothermemberwalletform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.form.field.Hidden'
    ],

    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Funding Another Member Wallet',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Fund Benediciary',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 10,
                                                    itemId: 'thismember',
                                                    margin: 10,
                                                    fieldLabel: 'Beneficiary',
                                                    labelWidth: 200,
                                                    name: 'name',
                                                    allowBlank: false,
                                                    editable: false,
                                                    displayField: 'name',
                                                    store: 'OtherMembersThatConnectedToThisMember',
                                                    valueField: 'id'
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    margin: 10,
                                                    text: '...'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Voucher Number',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 10,
                                                    itemId: 'thisvouchernumberBox',
                                                    margin: 10,
                                                    fieldLabel: 'Voucher Number',
                                                    labelWidth: 200,
                                                    name: 'voucher_number',
                                                    allowBlank: false
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'totalfundvalueContainer',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Total Voucher Value',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 10,
                                                    itemId: 'thistotalvouchervalueBox',
                                                    margin: 10,
                                                    fieldLabel: 'Total Voucher Value (=N=)',
                                                    labelWidth: 200,
                                                    name: 'voucher_value',
                                                    allowBlank: false
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            hidden: true,
                            itemId: 'totalfundvaluefordisplayContainer',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Total Voucher Value',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 10,
                                                    margin: 10,
                                                    fieldLabel: 'Total Voucher Value (=N=)',
                                                    labelWidth: 200,
                                                    name: 'total_voucher_value_display'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'unallocatedfundContainer',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Unallocated Voucher Value',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    flex: 10,
                                                    itemId: 'thisvoucherBox',
                                                    margin: 10,
                                                    fieldLabel: 'Unallocated Voucher Value(=N=)',
                                                    labelWidth: 200,
                                                    name: 'remaining_voucher_value',
                                                    allowBlank: false,
                                                    minValue: 0
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            hidden: true,
                            itemId: 'unallocatedfundfordisplayContainer',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Unallocated Voucher Value',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 10,
                                                    margin: 10,
                                                    fieldLabel: 'Unallocated Voucher Value(=N=)',
                                                    labelWidth: 200,
                                                    name: 'remaining_voucher_value_display'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Usage Comencement Date',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    flex: 10,
                                                    margin: 10,
                                                    fieldLabel: 'Usage Commencement Date',
                                                    labelWidth: 200,
                                                    name: 'usage_commencement_date',
                                                    allowBlank: false,
                                                    editable: false,
                                                    format: 'd/m/Y',
                                                    minValue: '01/01/1970',
                                                    submitFormat: 'm/d/Y'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'newvouchervalueformemberContainer',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Fund Value',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    flex: 10,
                                                    itemId: 'thisvoucherfundingBox',
                                                    margin: 10,
                                                    fieldLabel: 'Value (=N=)',
                                                    labelWidth: 200,
                                                    name: 'allocated_voucher_value',
                                                    minValue: 0
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            hidden: true,
                            itemId: 'newvouchervalueformemberfordisplayContainer',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Fund Value',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 10,
                                                    itemId: 'thisvoucherfundingBox',
                                                    margin: 10,
                                                    fieldLabel: 'Value (=N=)',
                                                    labelWidth: 200,
                                                    name: 'allocated_voucher_value_display'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            hidden: true,
                            itemId: 'existingvouchervalueformemberContainer',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Existing Fund Value',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 10,
                                                    itemId: 'thisvoucherfundingBox',
                                                    margin: 10,
                                                    fieldLabel: 'Existing Value (=N=)',
                                                    labelWidth: 200,
                                                    name: 'existing_voucher_value'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            hidden: true,
                            itemId: 'topupvouchervalueContainer',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Topup Fund Value',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    flex: 10,
                                                    itemId: 'topupthisvoucherfundingBox',
                                                    margin: 10,
                                                    fieldLabel: 'Topup Value (=N=)',
                                                    labelWidth: 200,
                                                    name: 'topup_voucher_value',
                                                    minValue: 0
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 0.5,
                            items: [
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            flex: 10,
                                            itemId: 'fundingmemberwallettermCheckbox',
                                            name: 'terms_and_conditions',
                                            boxLabel: 'I accept terms & conditions',
                                            inputValue: '1'
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            disabled: true,
                                            itemId: 'termsBtn',
                                            text: '...'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'voucher_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'wallet_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'operation'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'status'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            hidden: true,
                            itemId: 'fundamemberwalletBtn',
                            text: 'Fund Wallet'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            hidden: true,
                            itemId: 'activateamemberfundBtn',
                            text: 'Activate This Member Fund'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            hidden: true,
                            itemId: 'suspendamemberfundBtn',
                            text: 'Suspend This Member Fund'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            hidden: true,
                            itemId: 'unsuspendamemberfundBtn',
                            text: 'Unsuspend This Member Fund'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            hidden: true,
                            itemId: 'removebeneficiaryBtn',
                            text: 'Remove Beneficiary'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            hidden: true,
                            itemId: 'topupbeneficiaryfundBtn',
                            text: 'Topup Beneficiary Fund'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});