/*
 * File: app/view/HamperRedirectionForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.HamperRedirectionForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.hamperredirectionform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.button.Button',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Radio',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.form.field.Hidden'
    ],

    height: 620,
    width: 500,
    bodyPadding: 10,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1.6,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'fieldset',
                            title: 'Hamper & gift Info',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: 5,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 10,
                                            fieldLabel: 'Hamper & Gift Label',
                                            labelWidth: 130,
                                            name: 'hamper_label',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'viewhampercontentBtn',
                                            margin: '0 0 0 5',
                                            text: '...'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: 5,
                                    layout: 'anchor',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            fieldLabel: 'How many hampers & gift?',
                                            labelWidth: 170,
                                            name: 'number_of_hampers_delivered',
                                            readOnly: true,
                                            allowBlank: false,
                                            minValue: 1
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 2.5,
                    itemId: 'scheduledeliveryaddressContainer',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 3.5,
                            margin: '10 0 0 0',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    title: '',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    itemId: 'selectedDeliveryRegisteredAddressCheckbox',
                                                    name: 'scheduled_delivery_address',
                                                    boxLabel: 'This is the address where this hamper & gift was scheduled to be delivered',
                                                    checked: true,
                                                    inputValue: '1'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 5,
                                            itemId: 'thisscheduledaddressContainer',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: 'anchor',
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            anchor: '100%',
                                                            itemId: 'primaryCountryCombo',
                                                            fieldLabel: 'Country',
                                                            name: 'country',
                                                            readOnly: true,
                                                            allowBlank: false,
                                                            editable: false,
                                                            displayField: 'name',
                                                            store: 'Countries',
                                                            valueField: 'id'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: 'anchor',
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            anchor: '100%',
                                                            itemId: 'primaryStateCombo',
                                                            fieldLabel: 'State/Region',
                                                            name: 'state',
                                                            readOnly: true,
                                                            allowBlank: false,
                                                            editable: false,
                                                            displayField: 'name',
                                                            queryMode: 'local',
                                                            store: 'StatesInACountry',
                                                            valueField: 'id'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: 'anchor',
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            anchor: '100%',
                                                            itemId: 'primaryCityCombo',
                                                            fieldLabel: 'City/County',
                                                            name: 'city',
                                                            readOnly: true,
                                                            allowBlank: false,
                                                            editable: false,
                                                            displayField: 'name',
                                                            queryMode: 'local',
                                                            store: 'CitiesInAState',
                                                            valueField: 'id'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: 'anchor',
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            anchor: '100%',
                                                            fieldLabel: 'Address',
                                                            name: 'place_of_delivery',
                                                            allowBlank: false
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 3.8,
                    disabled: true,
                    itemId: 'newaddressestochoosefromContainer',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'fieldset',
                            margin: 5,
                            title: 'Redirect the delivery of this hamper & gift to any of these address locations',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    itemId: 'delivertoregisterprimaryaddressContainer',
                                    margin: 3,
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Deliver to my registered primary address location',
                                            items: [
                                                {
                                                    xtype: 'radiofield',
                                                    itemId: 'registeredAddressForRedirectionRadio',
                                                    name: 'delivery_address_option',
                                                    boxLabel: 'Deliver this hamper & gift  to my registered primary address location',
                                                    inputValue: 'registered_address'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 4,
                                    itemId: 'newaddressforhamperdeliveryContainer',
                                    margin: 3,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 3.5,
                                            margin: '10 0 0 0',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'fieldset',
                                                    flex: 1,
                                                    title: '',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            flex: 1,
                                                            items: [
                                                                {
                                                                    xtype: 'radiofield',
                                                                    itemId: 'nonRegisteredAddressForRedirectionRadio',
                                                                    name: 'delivery_address_option',
                                                                    boxLabel: 'Deliver this hamper & gift to this address location',
                                                                    inputValue: 'preferred_address'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            flex: 5,
                                                            itemId: 'deliveryaddresscontainer',
                                                            layout: {
                                                                type: 'vbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'container',
                                                                    flex: 1,
                                                                    layout: 'anchor',
                                                                    items: [
                                                                        {
                                                                            xtype: 'combobox',
                                                                            anchor: '100%',
                                                                            fieldLabel: 'Country',
                                                                            name: 'new_delivery_country',
                                                                            editable: false,
                                                                            displayField: 'name',
                                                                            store: 'Countries',
                                                                            valueField: 'id'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'container',
                                                                    flex: 1,
                                                                    layout: 'anchor',
                                                                    items: [
                                                                        {
                                                                            xtype: 'combobox',
                                                                            anchor: '100%',
                                                                            fieldLabel: 'State/Region',
                                                                            name: 'new_delivery_state',
                                                                            editable: false,
                                                                            displayField: 'name',
                                                                            store: 'States',
                                                                            valueField: 'id'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'container',
                                                                    flex: 1,
                                                                    layout: 'anchor',
                                                                    items: [
                                                                        {
                                                                            xtype: 'combobox',
                                                                            anchor: '100%',
                                                                            fieldLabel: 'City/County',
                                                                            name: 'new_delivery_city',
                                                                            editable: false,
                                                                            displayField: 'name',
                                                                            store: 'Cities',
                                                                            valueField: 'id'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'container',
                                                                    flex: 1,
                                                                    layout: 'anchor',
                                                                    items: [
                                                                        {
                                                                            xtype: 'textfield',
                                                                            anchor: '100%',
                                                                            fieldLabel: 'Address',
                                                                            name: 'new_delivery_address'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1.1,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'fieldset',
                            margin: 5,
                            title: 'Select the preferred hamper delivery type for this hamper & gift',
                            items: [
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            flex: 15,
                                            itemId: 'deliverytypeCombo',
                                            margin: 5,
                                            fieldLabel: 'Delivery Type',
                                            labelWidth: 120,
                                            name: 'delivery_type',
                                            editable: false,
                                            displayField: 'delivery_name',
                                            store: 'DeliveryType',
                                            valueField: 'delivery_type'
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'deliverytypeBtn',
                                            margin: 5,
                                            text: '...'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 0.5,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    flex: 10,
                                    itemId: 'redirectTermsAndConditionsCheckbox',
                                    margin: 5,
                                    name: 'terms_and_conditions',
                                    boxLabel: 'I accepts terms & conditions',
                                    inputValue: '1'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    disabled: true,
                                    itemId: 'termsBtn',
                                    margin: '5 15 5 10',
                                    text: '...'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'hamper_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'beneficiary_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'operation'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            itemId: 'redirecthamperdeliveryBtn',
                            iconCls: 'add',
                            text: 'Redirect Hamper Delivery'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});