/*
 * File: app/view/InvocationOfAnEscrowForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.InvocationOfAnEscrowForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.invocationofanescrowform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.field.HtmlEditor',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.form.field.Hidden'
    ],

    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    margin: 5,
                    title: 'Invocation of a Product Escrow',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 5,
                                    title: 'Product Code',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 10,
                                                    itemId: 'thisescrowedproductBox',
                                                    margin: '3 0 0 0',
                                                    fieldLabel: 'Product Code',
                                                    name: 'product_code',
                                                    readOnly: true,
                                                    allowBlank: false
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    itemId: 'thisescrowedproductBtn',
                                                    margin: '0 0 0 3',
                                                    text: '...'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 5,
                                    title: 'Escrow Number',
                                    items: [
                                        {
                                            xtype: 'container',
                                            margin: 5,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 10,
                                                    itemId: 'thisproductescrowBox',
                                                    margin: '3 0 0 0',
                                                    fieldLabel: 'Escrow Number',
                                                    name: 'escrow_number',
                                                    readOnly: true,
                                                    allowBlank: false
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    itemId: 'previewescrowBtn',
                                                    margin: '0 0 0 3',
                                                    text: '...'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 2,
                            itemId: 'escrowAgreement',
                            margin: 5,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    margin: 5,
                                    layout: 'fit',
                                    title: 'Reason for the Invocation',
                                    items: [
                                        {
                                            xtype: 'htmleditor',
                                            height: 150,
                                            fieldLabel: 'Reason',
                                            name: 'reason_for_invocation'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 0.5,
                            margin: 5,
                            items: [
                                {
                                    xtype: 'container',
                                    margin: 5,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            flex: 10,
                                            itemId: 'escrowtermCheckbox',
                                            name: 'terms_and_conditions',
                                            boxLabel: 'I accept the terms & conditions for the invocation of an escrow',
                                            inputValue: '1'
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            disabled: true,
                                            itemId: 'termsBtn',
                                            text: '...'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'escrow_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'quote_id',
                    value: 0
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'product_id',
                    value: 0
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'is_escrowed',
                    value: 0
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'is_quoted',
                    value: 0
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'is_futures',
                    value: 0
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'quantity',
                    value: 0
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            itemId: 'invokethisescrowBtn',
                            text: 'Invoke Escrow'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});