/*
 * File: app/view/MakeAConsumptionDecisionForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.MakeAConsumptionDecisionForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.makeaconsumptiondecisionform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    height: 250,
    itemId: '',
    width: 400,
    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    margin: 5,
                    title: 'Make a  Decision',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'radiogroup',
                            flex: 1,
                            margin: 3,
                            width: 400,
                            columns: 1,
                            items: [
                                {
                                    xtype: 'radiofield',
                                    itemId: 'buyDecisionRadio',
                                    name: 'decision',
                                    boxLabel: 'Buy It (You can schedule payments under this option)',
                                    checked: true,
                                    inputValue: '1'
                                },
                                {
                                    xtype: 'radiofield',
                                    itemId: 'rentDecisionRadio',
                                    name: 'decision',
                                    boxLabel: 'Rent It',
                                    inputValue: '1'
                                },
                                {
                                    xtype: 'radiofield',
                                    itemId: 'asAServiceDecisionRadio',
                                    name: 'decision',
                                    boxLabel: 'As a Service',
                                    inputValue: '1'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            itemId: 'buyitBtn',
                            text: 'Buy It'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'rentitBtn',
                            text: 'Rent It'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'asaserviceBtn',
                            text: 'As a Service'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});