/*
 * File: app/view/MakeSubscriptionPaymentForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.MakeSubscriptionPaymentForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.makesubscriptionpaymentform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Radio',
        'Ext.form.field.Number',
        'Ext.form.field.Display',
        'Ext.form.field.File',
        'Ext.button.Button',
        'Ext.form.field.Hidden'
    ],

    height: 704,
    width: 600,
    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    margin: 10,
                    title: 'Subscription Payment',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            flex: 1,
                            margin: 10,
                            title: 'Payments',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    flex: 1.5,
                                    margin: 10,
                                    title: 'Subscription Detail',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            itemId: 'typeCombo',
                                            margin: 5,
                                            fieldLabel: 'Membership Type',
                                            labelWidth: 150,
                                            name: 'membership_type',
                                            editable: false,
                                            displayField: 'name',
                                            store: 'MembershipTypes',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 3,
                                            itemId: 'subscriptionTypeContainer',
                                            margin: 5,
                                            layout: 'fit',
                                            items: [
                                                {
                                                    xtype: 'fieldset',
                                                    margin: 5,
                                                    title: 'Subscription Type',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'radiofield',
                                                            flex: 1,
                                                            itemId: 'monthlySubscriptionRadio',
                                                            name: 'subscription_type',
                                                            boxLabel: 'Monthly',
                                                            checked: true,
                                                            inputValue: 'monthly'
                                                        },
                                                        {
                                                            xtype: 'radiofield',
                                                            flex: 1,
                                                            itemId: 'yearlySubscriptionRadio',
                                                            name: 'subscription_type',
                                                            boxLabel: 'Yearly',
                                                            inputValue: 'yearly'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'numberfield',
                                            flex: 1,
                                            hidden: true,
                                            itemId: 'numberofyearsField',
                                            margin: 5,
                                            fieldLabel: 'Number of Years',
                                            labelWidth: 150,
                                            name: 'number_of_years',
                                            minValue: 1
                                        },
                                        {
                                            xtype: 'numberfield',
                                            flex: 1,
                                            itemId: 'numberofmonthsField',
                                            margin: 5,
                                            fieldLabel: 'Number of Months',
                                            labelWidth: 150,
                                            name: 'number_of_months',
                                            minValue: 1
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    itemId: 'paymentSummaryContainer',
                                    margin: 10,
                                    title: 'Payment Summary',
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%',
                                            fieldLabel: 'Total Subscription(=N=)',
                                            labelWidth: 170,
                                            name: 'gross_for_display'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%',
                                            fieldLabel: 'Applicable Discount(=N=)',
                                            labelWidth: 170,
                                            name: 'discount_for_display'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%',
                                            fieldLabel: 'Net Amount(=N=)',
                                            labelWidth: 170,
                                            name: 'net_for_display'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            flex: 1,
                            margin: 10,
                            title: 'Picture',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    flex: 8,
                                    margin: 10,
                                    title: 'Upload User Picture(.png & .jpg formats)',
                                    items: [
                                        {
                                            xtype: 'filefield',
                                            anchor: '100%',
                                            fieldLabel: 'User Picture',
                                            name: 'picture',
                                            buttonOnly: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    margin: 10,
                                    title: 'Terms & Conditions',
                                    items: [
                                        {
                                            xtype: 'container',
                                            margin: '',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    flex: 5,
                                                    itemId: 'termCheckbox',
                                                    name: 'is_term_acceptable',
                                                    boxLabel: 'Accept Terms & Conditions',
                                                    inputValue: '1'
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 3.2,
                                                    disabled: true,
                                                    itemId: 'termsBtn',
                                                    margin: '0 0 0 3',
                                                    text: 'Terms & Conditions'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'numberfield',
                    hidden: true,
                    itemId: 'grossField',
                    margin: 10,
                    fieldLabel: 'Label',
                    name: 'gross'
                },
                {
                    xtype: 'numberfield',
                    hidden: true,
                    itemId: 'discountedField',
                    margin: 10,
                    fieldLabel: 'Label',
                    name: 'discount'
                },
                {
                    xtype: 'numberfield',
                    hidden: true,
                    itemId: 'netamountField',
                    margin: 10,
                    fieldLabel: 'Label',
                    name: 'net'
                },
                {
                    xtype: 'hiddenfield',
                    margin: 10,
                    fieldLabel: 'Label',
                    name: 'operation',
                    value: 'registration'
                }
            ]
        });

        me.callParent(arguments);
    }

});