/*
 * File: app/view/OccurrenceProductBeyondSixMonthsWin.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.OccurrenceProductBeyondSixMonthsWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.occurrenceproductbeyondsixmonthswin',

    requires: [
        'Cobuy.view.OccurrenceProductBeyondSixMonthsGrid',
        'Ext.grid.Panel',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Separator',
        'Ext.button.Button'
    ],

    height: 500,
    width: 1000,
    layout: 'fit',
    title: 'A Product Transaction History',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'occurrenceproductbeyondsixmonthsgrid'
                },
                {
                    xtype: 'form',
                    hidden: true,
                    bodyPadding: 10,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'product_id'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'closeBtn',
                            iconCls: 'delete',
                            text: 'Close'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});