/*
 * File: app/view/PaasInformationForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.PaasInformationForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.paasinformationform',

    requires: [
        'Ext.Img',
        'Ext.form.FieldSet',
        'Ext.form.Label',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    height: 600,
    width: 600,
    bodyPadding: 10,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 2,
                    margin: 5,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'image',
                                    margin: 5,
                                    src: '../admin.oneroof.com.ng/cobuy_images/home/options_image_4.jpg'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 3,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Overview',
                                    items: [
                                        {
                                            xtype: 'label',
                                            html: '<ul style="list-style-type:square">   <li>In this concept, several products are allocated to a bucket</li>   <li>Customers meet their needs by subscribing to a bucket</li>   <li>A subscriber is entitled to request and use any of the products in a bucket within the subscription period</li>   <li>Only one item is allowed to be consumed at any given time through a subscription path</li>   <li>If there is a need to consume additional item in a bucket simulteneously, another separate subscription will have to be made on the bucket</li>   <li>You can subscribe to as many buckets as you see value in</li> </ul>'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    margin: 5,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 4,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Product Ownership',
                                    items: [
                                        {
                                            xtype: 'label',
                                            html: '<ul style="list-style-type:square">   <li>Oneroof maintains the ownership of every product in a bucket while the customers enjoy the benefits of it.</li> </ul>'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'image',
                                    src: '../admin.oneroof.com.ng/cobuy_images/home/paas_image.png'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    margin: 5,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'image',
                                    src: '../admin.oneroof.com.ng/cobuy_images/home/option_image_1.jpg'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 4,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Subscription',
                                    items: [
                                        {
                                            xtype: 'label',
                                            html: '<ul style="list-style-type:square">   <li>Subscription to a bucket confers the right to use any product in the bucket to the subscribers</li>   <li>Subscription elapses when renewals are not effected</li>  </ul>'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1.5,
                    margin: 5,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 4,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Benefits',
                                    items: [
                                        {
                                            xtype: 'label',
                                            html: ' <ul style="list-style-type:square">   <li>It reduces the cost of the value derived from a product while completely meeting the need of the customer</li>   <li>It makes quality and luxurious products affordable to virtually anybody that needs them</li>   <li>It completely eliminates waste in product  consumption  and value appreciation</li>    <li>It provides much savings to the customer</li>    <li>It provides varieties of quality product for a customer to use at an affordable cost</li> </ul>'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'image',
                                    src: '../admin.oneroof.com.ng/cobuy_images/home/option_image_2.jpg'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'closeBtn',
                            iconCls: 'delete',
                            text: 'Close'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            itemId: 'contactusBtn',
                            iconCls: 'download',
                            text: 'Need More Information?'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});