/*
 * File: app/view/PartHeaderPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.PartHeaderPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.partheaderpanel',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator'
    ],

    height: 250,
    width: 400,
    autoScroll: true,
    bodyStyle: 'background:black; padding:10px;',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'aboutfaasBtn',
                            style: 'background:#2CE6F7;',
                            text: 'Farming As A Service(FaaS)'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'aboutpaasBtn',
                            style: 'background:#2CE6F7;',
                            text: 'Product As A Service(PaaS)'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});