/*
 * File: app/view/PaymentSummaryForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.PaymentSummaryForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.paymentsummaryform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.form.field.Hidden'
    ],

    height: 250,
    itemId: 'summaryform',
    width: 400,
    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Summary of Payment',
                    items: [
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            fieldLabel: 'Amount(=N=)',
                            name: 'amount'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            fieldLabel: 'Order Number',
                            name: 'order_number'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            fieldLabel: 'Invoice Number',
                            name: 'invoice_number'
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'terms_and_conditions'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'hamper_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'beneficiary_id'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            itemId: 'payBtn',
                            loader: {
                                // url: "/paystack.php?amount=250099&&email=uche.ngadi@controlsoftltd.com&&ref=1122-667-9000-81",
                                url: '/paystack.php',
                                params: {
                                    amount: Ext.getCmp('mainviewport').down('#collectible').down('hiddenfield[name=amount]').getValue(),
                                    email: Ext.getCmp('mainviewport').down('#collectible').down('hiddenfield[name=email]').getValue(),
                                    ref: Ext.getCmp('mainviewport').down('#collectible').down('hiddenfield[name=order_number]').getValue(),
                                    membership_number: Ext.getCmp('mainviewport').down('#collectible').down('hiddenfield[name=membership_number]').getValue(),
                                    invoice_number: Ext.getCmp('mainviewport').down('#collectible').down('hiddenfield[name=invoice_number]').getValue()
                                },
                                autoLoad: true,
                                scripts: true
                            },
                            iconCls: 'payment',
                            text: 'Make Payment'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});