/*
 * File: app/view/ProductSubscriptionForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.ProductSubscriptionForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.productsubscriptionform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.Label',
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Boolean',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Separator'
    ],

    height: 250,
    id: 'productsubscriptioncentral',
    width: 400,
    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Product Subscription Central',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            flex: 1,
                            margin: '0 0 0 10',
                            autoScroll: true,
                            title: 'Product Subscription Manager',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 2
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            margin: 10,
                                            title: 'Product for Subscription',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    margin: 3,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 11,
                                                            itemId: 'productSubscriptionBox',
                                                            fieldLabel: 'Enter the required Product Code',
                                                            labelWidth: 200,
                                                            name: 'product',
                                                            emptyText: 'enter product code'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            flex: 2,
                                                            itemId: 'subscribeBtn',
                                                            text: 'Subscribe'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            flex: 1,
                                                            itemId: 'subscribeproductBtn',
                                                            margin: '0 0 0 3',
                                                            text: '...'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 2,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'fieldset',
                                                    margin: 10,
                                                    title: 'How to get a product code',
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            html: '<center><em>On the Store Main Page,Double click on the product  and get the Product Code from the displayed window</em><center>'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            flex: 1.2,
                            margin: '0 0 0 10',
                            autoScroll: true,
                            layout: 'fit',
                            title: 'Product Subscription & Delivery Scheduling Manager',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'productsubscriptionGrid',
                                    itemId: 'productsubscriptionGrid',
                                    autoScroll: true,
                                    title: 'List of  Products that you subscribed to',
                                    store: 'ProductsSubscribedToByMember',
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            width: 40,
                                            dataIndex: 'string',
                                            text: 'S/n'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'status',
                                            text: 'Status'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'topup_status',
                                            text: 'Top up Status'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'type',
                                            text: 'Type'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                var productStore = Ext.getStore('AllProducts');
                                                var product = productStore.findRecord('id', value);
                                                return product!== null ? product.get('name'): value;
                                            },
                                            width: 250,
                                            dataIndex: 'product_id',
                                            text: 'Product'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 250,
                                            dataIndex: 'subscription_quantity',
                                            text: 'Subscription Total Quantity'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 250,
                                            dataIndex: 'top_up_quantity',
                                            text: 'Top up Quantity'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 250,
                                            dataIndex: 'per_delivery_quantity',
                                            text: 'Per Delivery Quantity'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 250,
                                            dataIndex: 'remaining_subscription_quantity',
                                            text: 'Subscription Remaining Quantity'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 250,
                                            dataIndex: 'need_escrow_agreement',
                                            text: 'Escrowed Needed?'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 250,
                                            dataIndex: 'is_escrow_accepted',
                                            text: 'Escrowed Accepted?'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 150,
                                            dataIndex: 'day_of_delivery',
                                            text: 'Day of Delivery'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 150,
                                            dataIndex: 'week_of_delivery',
                                            text: 'Week of Delivery'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 150,
                                            dataIndex: 'delivery_frequency',
                                            text: 'Delivery Frequency'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            width: 150,
                                            dataIndex: 'date_of_first_delivery',
                                            text: 'Date of First Delivery'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            width: 150,
                                            dataIndex: 'date_of_last_delivery',
                                            text: 'Date of Last Delivery'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            width: 150,
                                            dataIndex: 'date_of_next_delivery',
                                            text: 'Date of Next Delivery'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            width: 150,
                                            dataIndex: 'date_product_was_subscribed_to_member',
                                            text: 'Date of Product Subscription'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            width: 150,
                                            dataIndex: 'date_product_to_member_was_updated',
                                            text: 'Date Subscription was Updated'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                var userStore = Ext.getStore('AllMembers');
                                                var user = userStore.findRecord('id', value);
                                                if(user.get('middlename') === null || user.get('middlename') === undefined){
                                                    var name = user.get('firstname') + " " + user.get('lastname');
                                                }else{
                                                    var name = user.get('firstname') + " " + user.get('middlename') + " " + user.get('lastname');
                                                }

                                                return user!== null ? name: value;
                                            },
                                            width: 150,
                                            dataIndex: 'product_was_subscribed_by',
                                            text: 'Subscribed By'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                var userStore = Ext.getStore('AllMembers');
                                                var user = userStore.findRecord('id', value);
                                                if(user.get('middlename') === null || user.get('middlename') === undefined){
                                                    var name = user.get('firstname') + " " + user.get('lastname');
                                                }else{
                                                    var name = user.get('firstname') + " " + user.get('middlename') + " " + user.get('lastname');
                                                }

                                                return user!== null ? name: value;
                                            },
                                            width: 150,
                                            dataIndex: 'product_was_updated_by',
                                            text: 'Updated By'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    itemId: 'schedulethissubscriptiondeliveryBtn',
                                                    text: 'Schedule Delivery Frequency'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'unsubscribeBtn',
                                                    iconCls: 'delete_1',
                                                    text: 'Unsubscribe'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    disabled: true,
                                                    itemId: 'quantitytopupBtn',
                                                    text: 'Topup'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    disabled: true,
                                                    itemId: 'escrowsubscriptionBtn',
                                                    text: 'Escrow Subscription'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    disabled: true,
                                                    itemId: 'drawdownBtn',
                                                    text: 'Drawdown'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});