/*
 * File: app/view/ProductExtraInformationForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.ProductExtraInformationForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.productextrainformationform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.form.field.Hidden'
    ],

    height: 250,
    width: 1000,
    bodyPadding: 10,

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    flex: 1,
                    margin: '0 0 0 5',
                    title: 'Product Condition & Park Content',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 3,
                                    autoScroll: true,
                                    title: 'Product Condition',
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%',
                                            name: 'condition'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 3,
                                    autoScroll: true,
                                    title: 'List of Items in the Park',
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%',
                                            name: 'whats_in_a_park'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    flex: 1,
                    margin: '0 0 0 5',
                    autoScroll: true,
                    title: 'Product Description',
                    items: [
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            name: 'description'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    flex: 1,
                    margin: '0 0 0 5',
                    autoScroll: true,
                    title: 'Product Features',
                    items: [
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            name: 'feature'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    flex: 1,
                    margin: '0 0 0 5',
                    autoScroll: true,
                    title: 'Product Specfications',
                    items: [
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            name: 'specifications'
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'product_id'
                }
            ]
        });

        me.callParent(arguments);
    }

});