/*
 * File: app/view/QuoteResponseForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.QuoteResponseForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.quoteresponseform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.button.Button',
        'Ext.form.field.ComboBox',
        'Ext.form.field.File',
        'Ext.form.Label',
        'Ext.form.field.Number',
        'Ext.form.field.Radio',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.form.field.Hidden'
    ],

    height: 550,
    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Quote Reponse',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Quote Number',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 10,
                                                    itemId: 'thisquotenumberBox',
                                                    margin: '3 0 0 0',
                                                    fieldLabel: 'Quote Number',
                                                    name: 'quote_number',
                                                    readOnly: true,
                                                    allowBlank: false
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    itemId: 'thisquotedproductBtn',
                                                    margin: '0 0 0 3',
                                                    text: '...'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 0.9,
                            disabled: true,
                            itemId: 'escrowContainer',
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Escrow Agreement Facility',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    flex: 12,
                                                    itemId: 'acceptescrowCheckbox',
                                                    name: 'accept_escrow',
                                                    boxLabel: 'I accept the terms & conditions as stated in this escrow agreement',
                                                    inputValue: '1'
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    itemId: 'viewescrowBtn',
                                                    margin: '0 0 0 3',
                                                    text: 'View'
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1.5,
                                                    hidden: true,
                                                    itemId: 'previewescrowBtn',
                                                    margin: '0 0 0 3',
                                                    text: 'Preview'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 2.5,
                            disabled: true,
                            itemId: 'futuresContainer',
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Futures Agreement Facility',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Delivery Month',
                                            labelWidth: 150,
                                            name: 'delivery_month',
                                            readOnly: true,
                                            displayField: 'month',
                                            store: 'FutureMonthOfDelivery',
                                            valueField: 'code'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Delivery Year',
                                            labelWidth: 150,
                                            name: 'delivery_year',
                                            readOnly: true,
                                            displayField: 'year',
                                            store: 'FutureYearOfDelivery',
                                            valueField: 'code'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Payment Method',
                                            labelWidth: 150,
                                            name: 'payment_method',
                                            readOnly: true,
                                            displayField: 'name',
                                            store: 'FuturePaymentTypes',
                                            valueField: 'rate'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Payment Frequency',
                                            labelWidth: 150,
                                            name: 'staggered_payment_frequency',
                                            readOnly: true,
                                            displayField: 'frequency',
                                            store: 'FuturePaymentFrequency',
                                            valueField: 'code'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            anchor: '100%',
                                            itemId: 'acceptfuturesCheckbox',
                                            name: 'accept_futures',
                                            boxLabel: 'I accept the payment plan as detailed in this futures trading facility',
                                            inputValue: '1'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 2.2,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Ouote Response & Product Unique Video',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'filefield',
                                            flex: 1,
                                            itemId: 'uploadquotationfile',
                                            margin: 5,
                                            fieldLabel: 'Upload Quotation file (in .pdf)',
                                            labelWidth: 450,
                                            name: 'quotation_file',
                                            buttonOnly: true
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            itemId: 'productvideoContainer',
                                            margin: 5,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    flex: 1.5,
                                                    itemId: 'salesPitchVideoCheckbox',
                                                    name: 'is_with_video',
                                                    boxLabel: 'Want to include Sales Pitch Video',
                                                    inputValue: '1'
                                                },
                                                {
                                                    xtype: 'filefield',
                                                    flex: 2,
                                                    disabled: true,
                                                    itemId: 'salespitchVideoFile',
                                                    fieldLabel: 'Upload a Sale\'s Pitch (in .mp4)',
                                                    labelWidth: 211,
                                                    name: 'video_filename',
                                                    buttonOnly: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            hidden: true,
                                            itemId: 'viewquotationfile',
                                            margin: 5,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    flex: 10,
                                                    margin: 3,
                                                    text: 'View This Quotation File'
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    itemId: 'viewquotationBtn',
                                                    margin: 3,
                                                    text: 'View'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            hidden: true,
                                            itemId: 'viewproductdemoContainer',
                                            margin: 5,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    flex: 10,
                                                    margin: 3,
                                                    text: 'Watch our Sale\'s Pitch'
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    itemId: 'quotevideoBtn',
                                                    margin: 3,
                                                    text: 'View'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'numberfield',
                                            flex: 1,
                                            itemId: 'amountquotedBox',
                                            margin: 5,
                                            fieldLabel: 'Total Amount Quoted/Including the delivery cost (=N=)',
                                            labelWidth: 320,
                                            name: 'total_amount_quoted',
                                            value: 0.00,
                                            allowBlank: false,
                                            minValue: 0
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 0.9,
                            itemId: 'termsandconditions',
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Quotation Terms & Conditions',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    flex: 12,
                                                    itemId: 'quotationtermsandconditionsCheckbox',
                                                    margin: '0 0 0 3',
                                                    name: 'terms_and_conditions',
                                                    boxLabel: 'I accept the terms & conditions for sending quotations on this platform',
                                                    inputValue: '1'
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    itemId: 'termsBtn',
                                                    text: '...'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 0.9,
                            hidden: true,
                            itemId: 'quotationdecision',
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Decision on Quotation',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'radiofield',
                                                    flex: 1,
                                                    itemId: 'acceptquotationRadio',
                                                    name: 'quotation_decision',
                                                    boxLabel: 'Quotation Accepted',
                                                    inputValue: 'accepted'
                                                },
                                                {
                                                    xtype: 'radiofield',
                                                    flex: 1,
                                                    margins: '0 0 0 3',
                                                    itemId: 'rejectquotationRadio',
                                                    fieldLabel: '',
                                                    name: 'quotation_decision',
                                                    boxLabel: 'Quotation Rejected',
                                                    inputValue: 'rejected'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'product_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'quote_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'escrow_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'need_escrow_agreement'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'future_trading'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'product_code'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'quantity_of_purchase'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'operation'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'quote_responder'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    itemId: 'maintoolbar',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            itemId: 'sendquotationBtn',
                            text: 'Send Quotation'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            hidden: true,
                            itemId: 'acceptquotationBtn',
                            text: 'Accept Quotation'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'rejectquotationBtn',
                            text: 'Reject Quotation'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'okBtn',
                            text: 'Ok'
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    hidden: true,
                    itemId: 'viewingtoolbar',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'okBtn',
                            text: 'Ok'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});