/*
 * File: app/view/ScheduleSubscriptionDeliveryForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.ScheduleSubscriptionDeliveryForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.schedulesubscriptiondeliveryform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.button.Button',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.form.field.Hidden'
    ],

    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    margin: 5,
                    title: 'Schedule Subscription Delivery',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 5,
                                    title: 'Product Code',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 10,
                                                    itemId: 'thisproductSubscriptionBox',
                                                    margin: '3 0 0 0',
                                                    fieldLabel: 'Product Code',
                                                    name: 'product_code',
                                                    readOnly: true,
                                                    allowBlank: false
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    itemId: 'thissubscribeproductBtn',
                                                    margin: '0 0 0 3',
                                                    text: '...'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 5,
                                    title: 'Day of delivery',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            margin: 10,
                                            fieldLabel: 'Day of delivery',
                                            labelWidth: 200,
                                            name: 'day_of_delivery',
                                            allowBlank: false,
                                            editable: false,
                                            displayField: 'day_of_delivery',
                                            store: 'SubscriptionDayOfDelivery',
                                            valueField: 'day_of_delivery'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 5,
                                    title: 'Week of Delivery',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            margin: 10,
                                            fieldLabel: 'Week of delivery',
                                            labelWidth: 200,
                                            name: 'week_of_delivery',
                                            allowBlank: false,
                                            editable: false,
                                            displayField: 'week_of_delivery',
                                            store: 'SusbcriptionWeekOfDelivery',
                                            valueField: 'week_of_delivery'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 5,
                                    title: 'Delivery Frequency',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            margin: 10,
                                            fieldLabel: 'Delivery Frequency',
                                            labelWidth: 200,
                                            name: 'delivery_frequency',
                                            allowBlank: false,
                                            editable: false,
                                            displayField: 'delivery_frequency',
                                            store: 'SubscriptionDeliveryFrequency',
                                            valueField: 'delivery_frequency'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 5,
                                    title: 'Date of first delivery',
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            anchor: '100%',
                                            margin: 10,
                                            fieldLabel: 'Date of first delivery',
                                            labelWidth: 200,
                                            name: 'date_of_first_delivery',
                                            editable: false,
                                            format: 'd/m/Y',
                                            submitFormat: 'm/d/Y'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1.5,
                            hidden: true,
                            itemId: 'deliverydrawdown',
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 5,
                                    title: 'First Delivery Drawdown',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            margin: 10,
                                            fieldLabel: 'Remaining quantity',
                                            labelWidth: 200,
                                            name: 'remaining_subscription_quantity',
                                            readOnly: true,
                                            editable: false
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            margin: 10,
                                            fieldLabel: 'Delivery Quantity',
                                            labelWidth: 200,
                                            name: 'per_delivery_quantity',
                                            editable: false,
                                            minValue: 1
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'subscription_type'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'product_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'is_delivery_scheduled'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'scheduledeliveryBtn',
                            text: 'Schedule Delivery'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});