/*
 * File: app/view/SideAdvetDataviewPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.SideAdvetDataviewPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sideadvetdataviewpanel',

    requires: [
        'Ext.panel.Panel',
        'Ext.form.Label',
        'Ext.view.View',
        'Ext.XTemplate',
        'Ext.Img'
    ],

    itemId: 'sideadvetdataviewpanel',
    margin: 5,
    header: false,
    title: 'My Panel',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            bodyStyle: {
                backgroundColor: '#DCDCDC'
            },
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    itemId: 'rentPanel',
                    margin: 5,
                    header: false,
                    title: 'My Panel',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            margin: 5,
                            layout: 'anchor',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'label',
                                    html: '<h2><center><strong>Product for Rent</strong></center></h2>'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 3.5,
                            margin: 5,
                            layout: 'fit',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'dataview',
                                    cls: 'my-dataview-cls',
                                    hidden: true,
                                    itemId: 'rentDataview',
                                    itemSelector: 'div.thumb-wrap',
                                    itemTpl: [
                                        '<tpl for=".">',
                                        '    <div style="float:left;padding:30px 30px 30px 15px;  "class=thumb-wrap id="id">',
                                        '        <div class=thumb><img src="../admin.oneroof.com.ng/cobuy_images/home/{for_rent}"  height="200" width="200"></div>',
                                        '        <div>',
                                        '          <b>{shortName} </b><br>',
                                        '            <b>{shortDesc} </b><br>',
                                        '            ',
                                        '       ',
                                        '        </div>',
                                        '        ',
                                        '    </tpl>',
                                        '<div class=x-clear></div>',
                                        '',
                                        '',
                                        ''
                                    ],
                                    store: 'HomePage'
                                },
                                {
                                    xtype: 'image',
                                    cls: 'ovAddComponentClickEvent',
                                    itemId: 'rentimage',
                                    style: {
                                        cursor: 'pointer'
                                    },
                                    src: '../admin.oneroof.com.ng/cobuy_images/home/rent_image.jpg'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    itemId: 'optionsPanel',
                    margin: 5,
                    header: false,
                    title: 'My Panel',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            margin: 5,
                            layout: 'anchor',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'label',
                                    html: '<h2><center><strong>"Product As A Service" Buckets</strong></center></h2>'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 3.2,
                            margin: 5,
                            layout: 'fit',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'dataview',
                                    cls: 'my-dataview-cls',
                                    hidden: true,
                                    itemId: 'paasDataview',
                                    itemSelector: 'div.thumb-wrap',
                                    itemTpl: [
                                        '<tpl for=".">',
                                        '    <div style="float:left;padding:30px 30px 30px 15px;  "class=thumb-wrap id="id">',
                                        '        <div class=thumb><img src="../admin.oneroof.com.ng/cobuy_images/home/{for_options}"  height="200" width="200"></div>',
                                        '        <div>',
                                        '          <b>{shortName} </b><br>',
                                        '            <b>{shortDesc} </b><br>',
                                        '            ',
                                        '       ',
                                        '        </div>',
                                        '        ',
                                        '    </tpl>',
                                        '<div class=x-clear></div>'
                                    ],
                                    store: 'HomePage'
                                },
                                {
                                    xtype: 'image',
                                    cls: 'ovAddComponentClickEvent',
                                    itemId: 'paasimage',
                                    style: {
                                        cursor: 'pointer'
                                    },
                                    src: '../admin.oneroof.com.ng/cobuy_images/home/paas_image.png'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    itemId: 'faasPanel',
                    margin: 5,
                    header: false,
                    title: 'My Panel',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            margin: 5,
                            layout: 'anchor',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'label',
                                    html: '<h2><center><strong>Farming As A Service</strong></center></h2>'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 3.2,
                            margin: 5,
                            layout: 'fit',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'dataview',
                                    cls: 'my-dataview-cls',
                                    hidden: true,
                                    itemId: 'faasDataview',
                                    itemSelector: 'div.thumb-wrap',
                                    itemTpl: [
                                        '<tpl for=".">',
                                        '    <div style="float:left;padding:30px 30px 30px 15px;  "class=thumb-wrap id="id">',
                                        '        <div class=thumb><img src="../admin.oneroof.com.ng/cobuy_images/home/{farming_services}"  height="200" width="200"></div>',
                                        '        <div>',
                                        '          <b>{shortName} </b><br>',
                                        '            <b>{shortDesc} </b><br>',
                                        '            ',
                                        '       ',
                                        '        </div>',
                                        '        ',
                                        '    </tpl>',
                                        '<div class=x-clear></div>'
                                    ],
                                    store: 'HomePage'
                                },
                                {
                                    xtype: 'image',
                                    cls: 'ovAddComponentClickEvent',
                                    itemId: 'faasimage',
                                    style: {
                                        cursor: 'pointer'
                                    },
                                    src: '../admin.oneroof.com.ng/cobuy_images/home/farming.jpg'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    itemId: 'less1000Panel',
                    margin: 5,
                    header: false,
                    title: 'My Panel',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            margin: 5,
                            layout: 'anchor',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'label',
                                    html: '<h2><center><strong>Less than N1,000 Products</strong></center></h2>'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 3.2,
                            margin: 5,
                            layout: 'fit',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'dataview',
                                    cls: 'my-dataview-cls',
                                    hidden: true,
                                    itemId: 'less1000Dataview',
                                    itemSelector: 'div.thumb-wrap',
                                    itemTpl: [
                                        '<tpl for=".">',
                                        '    <div style="float:left;padding:30px 30px 30px 15px;  "class=thumb-wrap id="id">',
                                        '        <div class=thumb><img src="../admin.oneroof.com.ng/cobuy_images/home/{less_than_1000}"  height="200" width="200"></div>',
                                        '        <div>',
                                        '          <b>{shortName} </b><br>',
                                        '            <b>{shortDesc} </b><br>',
                                        '            ',
                                        '       ',
                                        '        </div>',
                                        '        ',
                                        '    </tpl>',
                                        '<div class=x-clear></div>'
                                    ],
                                    store: 'HomePage'
                                },
                                {
                                    xtype: 'image',
                                    cls: 'ovAddComponentClickEvent',
                                    itemId: 'lessthan1000image',
                                    style: {
                                        cursor: 'pointer'
                                    },
                                    src: '../admin.oneroof.com.ng/cobuy_images/home/less1000_image_2.jpg'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    hidden: true,
                    itemId: 'salesPanel',
                    margin: 5,
                    header: false,
                    title: 'My Panel',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            margin: 5,
                            layout: 'anchor',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'label',
                                    html: '<h2><center><strong>Sales Promotions</strong></center></h2>'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 3.5,
                            margin: 5,
                            layout: 'fit',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'dataview',
                                    cls: 'my-dataview-cls',
                                    hidden: true,
                                    itemId: 'salesDataview',
                                    itemSelector: 'div.thumb-wrap',
                                    itemTpl: [
                                        '<tpl for=".">',
                                        '    <div style="float:left;padding:30px 30px 30px 15px;  "class=thumb-wrap id="id">',
                                        '        <div class=thumb><img src="../admin.oneroof.com.ng/cobuy_images/home/{products_on_sales}"  height="200" width="200"></div>',
                                        '        <div>',
                                        '          <b>{shortName} </b><br>',
                                        '            <b>{shortDesc} </b><br>',
                                        '            ',
                                        '       ',
                                        '        </div>',
                                        '        ',
                                        '    </tpl>',
                                        '<div class=x-clear></div>'
                                    ],
                                    store: 'HomePage'
                                },
                                {
                                    xtype: 'image',
                                    cls: 'ovAddComponentClickEvent',
                                    itemId: 'salesimage',
                                    style: {
                                        cursor: 'pointer'
                                    },
                                    src: '../admin.oneroof.com.ng/cobuy_images/home/sales_image_2.jpg'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    itemId: 'allproductsPanel',
                    margin: 5,
                    header: false,
                    title: 'My Panel',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            margin: 5,
                            layout: 'anchor',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'label',
                                    html: '<h2><center><strong>All Products\' Categories</strong></center></h2>'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 3.2,
                            itemId: 'allHomeProductCategoryPanel',
                            margin: 5,
                            layout: 'fit',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'dataview',
                                    cls: 'my-dataview-cls',
                                    hidden: true,
                                    itemId: 'allCategoryDataview',
                                    itemSelector: 'div.thumb-wrap',
                                    itemTpl: [
                                        '<tpl for=".">',
                                        '    <div style="float:left;padding:30px 30px 30px 15px;  "class=thumb-wrap id="id">',
                                        '        <div class=thumb><img src="../admin.oneroof.com.ng/cobuy_images/home/{all_categories}"  height="200" width="200"></div>',
                                        '        <div>',
                                        '          <b>{shortName} </b><br>',
                                        '            <b>{shortDesc} </b><br>',
                                        '            ',
                                        '       ',
                                        '        </div>',
                                        '        ',
                                        '    </tpl>',
                                        '<div class=x-clear></div>'
                                    ],
                                    store: 'HomePage'
                                },
                                {
                                    xtype: 'image',
                                    cls: 'ovAddComponentClickEvent',
                                    itemId: 'allcategoryimage',
                                    style: {
                                        cursor: 'pointer'
                                    },
                                    src: '../admin.oneroof.com.ng/cobuy_images/home/option_image_2.jpg'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    hidden: true,
                    margin: 5
                }
            ]
        });

        me.callParent(arguments);
    }

});