/*
 * File: app/view/TopUpSubscriptionForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.TopUpSubscriptionForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.topupsubscriptionform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.button.Button',
        'Ext.form.field.Number',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.form.field.Hidden'
    ],

    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    margin: 5,
                    title: 'Product Subscription TopUp',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 5,
                                    title: 'Product Code',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 10,
                                                    itemId: 'thisproductSubscriptionBox',
                                                    margin: '3 0 0 0',
                                                    fieldLabel: 'Product Code',
                                                    name: 'product_code',
                                                    readOnly: true,
                                                    allowBlank: false
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    itemId: 'thissubscribeproductBtn',
                                                    margin: '0 0 0 3',
                                                    text: '...'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 5,
                                    title: 'Total Subscribed Quantity',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            margin: 10,
                                            fieldLabel: 'Total Subscribed Quantity',
                                            labelWidth: 200,
                                            name: 'total_subscription_quantity',
                                            readOnly: true
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 5,
                                    title: 'Remaining Subscribed Quantity',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            margin: 10,
                                            fieldLabel: 'Remaining Quantity',
                                            labelWidth: 200,
                                            name: 'remaining_subscription_quantity',
                                            readOnly: true,
                                            minValue: 0
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margin: 5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    margin: 5,
                                    title: 'Topup Subscription Quantity',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            margin: 10,
                                            fieldLabel: 'Topup Quantity',
                                            labelWidth: 200,
                                            name: 'topup_quantity',
                                            allowBlank: false,
                                            minValue: 1
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'subscription_type'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'product_id'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'topupthissuibscriptionBtn',
                            text: 'TopUp'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'topupthispresuibscriptionBtn',
                            text: 'TopUp pre'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});