/*
 * File: app/view/WalletAndAllowancesForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.view.WalletAndAllowancesForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.walletandallowancesform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Boolean',
        'Ext.grid.column.Date',
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.form.field.Text'
    ],

    height: 250,
    id: 'walletcentral',
    width: 400,
    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Wallet & Allowances Central',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            flex: 2,
                            margin: '0 0 0 10',
                            autoScroll: true,
                            layout: 'fit',
                            title: 'Vouches Manager',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'membervoucherGrid',
                                    itemId: 'membervoucherGrid',
                                    autoScroll: true,
                                    title: 'Member Voucher List',
                                    store: 'MemberVouchers',
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            width: 40,
                                            dataIndex: 'string',
                                            text: 'S/n'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'status',
                                            text: 'Status'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 250,
                                            dataIndex: 'voucher_number',
                                            text: 'Voucher Number'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 250,
                                            dataIndex: 'voucher_value',
                                            text: 'Voucher Value'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 250,
                                            dataIndex: 'remaining_voucher_value',
                                            text: 'Remaining Voucher Value'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 250,
                                            dataIndex: 'purpose',
                                            text: 'Voucher Purpose'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 250,
                                            dataIndex: 'is_voucher_payment_confirmed',
                                            text: 'Is Voucher Payment Confirmed?'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 250,
                                            dataIndex: 'is_voucher_toppedup',
                                            text: 'Is Voucher Topped Up?'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            width: 250,
                                            dataIndex: 'topup_date',
                                            text: 'Topup Date'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 250,
                                            dataIndex: 'topup_value_status',
                                            text: 'Topup Status'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            width: 250,
                                            dataIndex: 'topup_value',
                                            text: 'Topup Value'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 250,
                                            dataIndex: 'is_topup_payment_confirmed',
                                            text: 'Is Topup Payment Confirmed?'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            width: 250,
                                            dataIndex: 'date_confirmed',
                                            text: 'Date Voucher Payment was Confirmed'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            width: 250,
                                            dataIndex: 'date_topup_confirmed',
                                            text: 'Date Topup Payment was Confirmed'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            width: 250,
                                            dataIndex: 'date_created',
                                            text: 'Date Created',
                                            format: 'd/m/Y'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                var userStore = Ext.getStore('AllMembers');
                                                var user = userStore.findRecord('id', value);
                                                if(user.get('middlename') === null || user.get('middlename') === undefined){
                                                    var name = user.get('firstname') + " " + user.get('lastname');
                                                }else{
                                                    var name = user.get('firstname') + " " + user.get('middlename') + " " + user.get('lastname');
                                                }

                                                return user!== null ? name: value;
                                            },
                                            width: 250,
                                            dataIndex: 'create_by',
                                            text: 'Created By'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 250,
                                            dataIndex: 'accepted_voucher_creation_and_user_terms',
                                            text: 'Accepted Voucher Terms & Conditions?'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 250,
                                            dataIndex: 'accepted_voucher_topup_terms',
                                            text: 'Accepted Voucher Topup Terms & Conditions?'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    itemId: 'createnewvoucherBtn',
                                                    text: 'Create New Voucher'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'topupBtn',
                                                    text: 'TopUp'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'limitvoucherBtn',
                                                    text: 'Limit Voucher Purchases'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    disabled: true,
                                                    itemId: 'fundownwalletBtn',
                                                    text: 'Fund Own Wallet'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    disabled: true,
                                                    itemId: 'allocateallowanceBtn',
                                                    text: 'Allocate Allowances to Others'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            flex: 1,
                            hidden: true,
                            margin: '0 0 0 10',
                            autoScroll: true,
                            layout: 'fit',
                            title: 'Product Purchase Limiters'
                        },
                        {
                            xtype: 'fieldset',
                            flex: 1.2,
                            margin: '0 0 0 10',
                            autoScroll: true,
                            title: 'Wallets Manager',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 2,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            id: 'memberwalletGrid',
                                            itemId: 'memberwalletGrid',
                                            autoScroll: true,
                                            title: 'Member Wallet',
                                            store: 'VouchersInAWallet',
                                            columns: [
                                                {
                                                    xtype: 'rownumberer',
                                                    width: 40,
                                                    dataIndex: 'string',
                                                    text: 'S/n'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'status',
                                                    text: 'Status'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    width: 250,
                                                    dataIndex: 'available_voucher_value',
                                                    text: 'Voucher Available Value'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                        var voucherStore = Ext.getStore('Vouchers');
                                                        var voucher = voucherStore.findRecord('id', value);
                                                        return voucher!== null ? voucher.get('voucher_number'): value;
                                                    },
                                                    width: 200,
                                                    dataIndex: 'voucher_id',
                                                    text: 'Voucher Number'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    width: 150,
                                                    dataIndex: 'actual_voucher_share',
                                                    text: 'Voucher Value'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    width: 150,
                                                    dataIndex: 'used_voucher_value',
                                                    text: 'Voucher Used Value'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    width: 150,
                                                    dataIndex: 'usage_commencement_date',
                                                    text: 'Usage Commencement Date',
                                                    format: 'd/m/Y'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                        var userStore = Ext.getStore('AllMembers');
                                                        var user = userStore.findRecord('id', value);
                                                        if(user.get('middlename') === null || user.get('middlename') === undefined){
                                                            var name = user.get('firstname') + " " + user.get('lastname');
                                                        }else{
                                                            var name = user.get('firstname') + " " + user.get('middlename') + " " + user.get('lastname');
                                                        }

                                                        return user!== null ? name: value;

                                                    },
                                                    width: 150,
                                                    dataIndex: 'voucher_was_added_by',
                                                    text: 'Voucher Owner'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    width: 150,
                                                    dataIndex: 'date_voucher_was_added_to_wallet',
                                                    text: 'Date Voucher Was Added',
                                                    format: 'd/m/Y'
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'productlimiterBtn',
                                                            text: 'View Voucher Product Limiter'
                                                        },
                                                        {
                                                            xtype: 'tbseparator'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'categorylimiterBtn',
                                                            text: 'View Voucher Category Limiter'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 2,
                                            items: [
                                                {
                                                    xtype: 'fieldset',
                                                    title: 'Wallet Total Available Value(=N=)',
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            margin: 10,
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    flex: 9,
                                                                    itemId: 'walletAvailablevalue',
                                                                    fieldLabel: 'Expendable Balance (=N=)',
                                                                    labelWidth: 170,
                                                                    name: 'wallet_available_value',
                                                                    readOnly: true
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    flex: 1,
                                                                    itemId: 'availablefundanalysisBtn',
                                                                    margin: '0 0 0 3',
                                                                    text: '...'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    flex: 1,
                                                                    itemId: 'refreshavailablevalueBtn',
                                                                    margin: '0 0 0 3',
                                                                    iconCls: 'refresh'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            margin: 10,
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    flex: 9,
                                                                    itemId: 'walletSuspendedFundValue',
                                                                    fieldLabel: 'Suspended Balance (=N=)',
                                                                    labelWidth: 170,
                                                                    name: 'wallet_suspended_value',
                                                                    readOnly: true
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    flex: 1,
                                                                    itemId: 'suspendedfundanalysisBtn',
                                                                    margin: '0 0 0 3',
                                                                    text: '...'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    flex: 1,
                                                                    itemId: 'refreshsuspendedfundvalueBtn',
                                                                    margin: '0 0 0 3',
                                                                    iconCls: 'refresh'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            margin: 10,
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    flex: 5,
                                                                    itemId: 'walletTotalValue',
                                                                    fieldLabel: 'Total Wallet Balance (=N=)',
                                                                    labelWidth: 170,
                                                                    name: 'wallet_total_value',
                                                                    readOnly: true
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});